package com.abigail.couponsproject.exceptions;

public enum ExceptionType {
	LOGIN_FAILED,
	COMPANY_CREATION_FAILED,
	ILLEGAL_COMPANY_CREATION,
	COMPANY_NOT_FOUND,
	COMPANY_REMOVAL_FAILED,
	COMAPNY_UPDATE_FAILED,
	ILLEGAL_COMPANY_UPDATE,
	COUPON_CREATION_FAILED,
	ILLEGAL_COUPON_CREATION,
	COUPON_NOT_AVAILABLE,
	COUPON_REMOVAL_FAILED,
	COUPON_UPDATE_FAILED,
	ILLEGAL_COUPON_UPDATE,
	COUPON_OUT_OF_STOCK,
	COUPON_EXPIRED,
	ILLEGAL_PURCHASE,
	CUSTOMER_CREATION_FAILED,
	ILLEGAL_CUSTOMER_CREATION,
	CUSTOMER_NOT_FOUND,
	CUSTOMER_REMOVAL_FAILED,
	CUSTOMER_UPDATE_FAILED,
	ILLEGAL_CUSTOMER_UPDATE,
	GENERAL_ERROR
}//ECustomExceptions
